title: Site Name
baseurl: /
permalink: /:title/
palette: blue
palettes:
  blue:
    sass:
      accent1: "#4167a6"
      accent2: "#3f8eb3"
      accent3: "#4ca07e"
      bg: "#253149"
  green:
    sass:
      accent1: "#2e9692"
      accent2: "#3aa4ca"
      accent3: "#b84d50"
      bg: "#20313d"
  purple:
    sass:
      accent1: "#5e42a6"
      accent2: "#5052b5"
      accent3: "#b74e91"
      bg: "#312450"
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
